// PATTERN: Memento

export enum ActionType {
  RENAME_LIST = 'RENAME_LIST',
  RENAME_CARD = 'RENAME_CARD',
  CHANGE_CARD_DESCRIPTION = 'CHANGE_CARD_DESCRIPTION',
  INITIAL_STATE = 'INITIAL_STATE',
}
